baseurl = "https://anandkanishka.com/"
languageCode = "en-us"
title = "Kanishka Anand"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section", "404"]

[permalinks]
    post = "/:title/"
    page = "/:title/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/anandkanishka/"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/manukanishka"

[params]
    mainSections = ["post"]

    description = ""


    [params.logo]
    url = "logo_2.jpg"
    width = 50
    height = 50
    alt = "observe & share"

    [params.icon]
    url = "logo_2.jpg"
